### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by luciusmagn** [bhoglo/projects#1]
https://github.com/bhoglo/projects/blob/a28d0a88dac332e4a9f80f53879f0b2f2d257e1a/syntax_and_variables_02/src/main.rs#L28

In Rust, to exit with a code different than 0, you use the `std::process::exit(code)` function

**Comment by luciusmagn** [comment]
See if that works for you :)

**Comment by bhoglo** [comment]
> https://github.com/bhoglo/projects/blob/a28d0a88dac332e4a9f80f53879f0b2f2d257e1a/syntax_and_variables_02/src/main.rs#L28
> 
> In Rust, to exit with a code different than 0, you use the `std::process::exit(code)` function

Thanks! I've added that but moved the line into the help function. Seems like it would make more sense there.
